set nu
set ts=4
set hlsearch
set autoread
au CursorHold * checktime

"Disabling swap files"
set noswapfile
"Organizing swap files"
"create a swp folder in ~/.vim/ and put all swap files in this folder"
"mkdir -p ~/.vim/swp"
"set directory=$HOME/.vim/swp//


"For Windows GVim"
"set guifont=Consolas:h12  

"colorscheme darblue

syntax on

" in insert mode key { auto completed { } for C 
imap { {<CR><CR>}<Esc>bi<Tab>
"inoremap { {<CR><CR>}<Esc>b 

"in insert mode for python"
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i
inoremap ' ''<Esc>i
inoremap " ""<Esc>i

